import 'package:mahindra_finance_task/models/user_details.dart';

const List hrd = [
  UserDetails(
      name: "Balram Naidu",
      id: "LOREM123456354",
      offered: "X,XX,XXX",
      current: "X,XX,XXX",
      priority: "Medium Priority",
      date: "05 Jun 23",
      daysLeft: 23,
      level: 10),
  UserDetails(
      name: "Rakesh Nair",
      id: "LOREM123456354",
      offered: "X,XX,XXX",
      current: "X,XX,XXX",
      priority: "High Priority",
      date: "05 Jun 23",
      daysLeft: 23,
      level: 10),
  UserDetails(
      name: "Krishna Ranshinge",
      id: "LOREM123456354",
      offered: "X,XX,XXX",
      current: "X,XX,XXX",
      priority: "Medium Priority",
      date: "05 Jun 23",
      daysLeft: 23,
      level: 10),
  UserDetails(
      name: "Kuldeep Patil",
      id: "LOREM123456354",
      offered: "X,XX,XXX",
      current: "X,XX,XXX",
      priority: "High Priority",
      date: "05 Jun 23",
      daysLeft: 23,
      level: 10),
  UserDetails(
      name: "Ajay Pangare",
      id: "LOREM123456354",
      offered: "X,XX,XXX",
      current: "X,XX,XXX",
      priority: "Low Priority",
      date: "05 Jun 23",
      daysLeft: 23,
      level: 10),
];

const List tech = [
  UserDetails(
      name: "Sagar Koli",
      id: "LOREM123456354",
      offered: "X,XX,XXX",
      current: "X,XX,XXX",
      priority: "Medium Priority",
      date: "05 Jun 23",
      daysLeft: 23,
      level: 10),
  UserDetails(
      name: "Mandar Khandangle",
      id: "LOREM123456354",
      offered: "X,XX,XXX",
      current: "X,XX,XXX",
      priority: "High Priority",
      date: "05 Jun 23",
      daysLeft: 23,
      level: 10),
  UserDetails(
      name: "Sonam Jha",
      id: "LOREM123456354",
      offered: "X,XX,XXX",
      current: "X,XX,XXX",
      priority: "Low Priority",
      date: "05 Jun 23",
      daysLeft: 23,
      level: 10),
  UserDetails(
      name: "Deepak Ranshinge",
      id: "LOREM123456354",
      offered: "X,XX,XXX",
      current: "X,XX,XXX",
      priority: "Medium Priority",
      date: "05 Jun 23",
      daysLeft: 23,
      level: 10),
  UserDetails(
      name: "Yadnesh Purav",
      id: "LOREM123456354",
      offered: "X,XX,XXX",
      current: "X,XX,XXX",
      priority: "High Priority",
      date: "05 Jun 23",
      daysLeft: 23,
      level: 10),
];

const List followUp = [
  UserDetails(
      name: "Hasan Haidade",
      id: "LOREM123456354",
      offered: "X,XX,XXX",
      current: "X,XX,XXX",
      priority: "Medium Priority",
      date: "05 Jun 23",
      daysLeft: 23,
      level: 10),
  UserDetails(
      name: "Pooja Kshtriya",
      id: "LOREM123456354",
      offered: "X,XX,XXX",
      current: "X,XX,XXX",
      priority: "High Priority",
      date: "05 Jun 23",
      daysLeft: 23,
      level: 10),
  UserDetails(
      name: "Archana Ranshinge",
      id: "LOREM123456354",
      offered: "X,XX,XXX",
      current: "X,XX,XXX",
      priority: "High Priority",
      date: "05 Jun 23",
      daysLeft: 23,
      level: 10),
  UserDetails(
      name: "Javed Ali",
      id: "LOREM123456354",
      offered: "X,XX,XXX",
      current: "X,XX,XXX",
      priority: "Low Priority",
      date: "05 Jun 23",
      daysLeft: 23,
      level: 10),
  UserDetails(
      name: "Anupriya Ali",
      id: "LOREM123456354",
      offered: "X,XX,XXX",
      current: "X,XX,XXX",
      priority: "Medium Priority",
      date: "05 Jun 23",
      daysLeft: 23,
      level: 10),
];
